### PR TITLE
feat: crowdin sync

### PR DESCRIPTION
**Pull request by DiamondMiner88**
Uploads/downloads crowdin translations every week or when strings.xml is modified and merges to master.

### CODE REVIEW

**Comment by baiorett** [comment]
hey, you can use integration tab on crowdin for that

**Comment by DiamondMiner88** [comment]
you remember how ugly the integration was
me when 2000 prs guhhh

**Comment by X1nto** [comment]
I don't think automatic merging is a good idea

**Comment by DiamondMiner88** [comment]
Hyperion does the same thing as this, and it works really well

**Comment by baiorett** [comment]
> you remember how ugly the integration was
> me when 2000 prs guhhh

mmm right

**Comment by baiorett** [comment]
and if i remember correctly the integrated bot has translations all on separate branch that is up with master

**Comment by X1nto** [comment]
> Hyperion does the same thing as this, and it works really well

Now imagine someone fucks up string templates in crowdin, bot pushes it and it's merged so now build is fucked up

**Comment by wingio** [comment]
i mean crowdin requires reviews on each translation

**Comment by X1nto** [comment]
meh fair then

**Comment by DiamondMiner88** [comment]
The only thing I'm not sure about is if it can push to master since it has branch protection trol

**Comment by X1nto** [comment]
I'll off the protection

**Review by X1nto — APPROVED** [review]

**Review by wingio — APPROVED** [review]

**Pull request merged**
